---
- name: Install dependencies
  apt:
    name:
      - gnupg1
      - apt-transport-https
      - dirmngr

- name: Add Ookla APT key
  apt_key:
    url: https://packagecloud.io/ookla/speedtest-cli/gpgkey

- name: Add Ookla APT repo
  apt_repository:
    repo: 'deb https://packagecloud.io/ookla/speedtest-cli/debian/ {{ ansible_distribution_release }} main'
    filename: ookla

- name: Install Speedtest
  apt:
    name:
      - speedtest
